ubc_ipeer_course_course:
    resource: "@UBCiPeerCourseBundle/Controller/CourseController.php"
    type: annotation

ubc_ipeer_course_group:
    resource: "@UBCiPeerCourseBundle/Controller/CourseGroupController.php"
    type: annotation

ubc_ipeer_course_enrollment:
    resource: "@UBCiPeerCourseBundle/Controller/EnrollmentController.php"
    type: annotation

