ub_ci_peer_course:
    resource: "@UBCiPeerCourseBundle/Resources/config/routing.yml"
    prefix:   /api

ub_ci_peer_user:
    resource: "@UBCiPeerUserBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

