<?php

namespace UBC\iPeer\CourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseGroupRepository extends EntityRepository
{
}
